# Generated by Django 5.1.3 on 2024-12-03 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='details.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('remaining_quantity_from_balance', models.PositiveIntegerField(default=0)),
                ('additional_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_cash_owed', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('advance_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.employee')),
            ],
        ),
    ]
