# Generated by Django 5.1.3 on 2024-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
