# Generated by Django 5.1.3 on 2024-11-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_producttransaction_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='remaining_quantity_from_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
