# Generated by Django 5.1.3 on 2024-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_producttransaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='additional_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='remaining_cash_owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
