# Generated by Django 5.1.3 on 2024-11-27 10:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_producttransaction_additional_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
